// This file is generated by Slice Machine. Update with care!

import ContentRelatsionship from './ContentRelatsionship';
import ImageGallery from './ImageGallery';
import ImageTest from './ImageTest';
import ImageText from './ImageText';
import LinksSlices from './LinksSlices';
import TextSlice from './TextSlice';

export {
	ContentRelatsionship,
	ImageGallery,
	ImageTest,
	ImageText,
	LinksSlices,
	TextSlice,
};

export const components = {
	content_relatsionship: ContentRelatsionship,
	image_gallery: ImageGallery,
	image_test: ImageTest,
	image_text: ImageText,
	links_slices: LinksSlices,
	text_slice: TextSlice,
};
