// This file is generated by Slice Machine. Update with care!

import ContentRelatsionship from './ContentRelatsionship';
import ImageGallery from './ImageGallery';
import ImageTest from './ImageTest';
import ImageText from './ImageText';
import LinksSlices from './LinksSlices';
import NewSlice from './NewSlice';
import TestSlice from './TestSlice';
import TextSlice from './TextSlice';

export {
	ContentRelatsionship,
	ImageGallery,
	ImageTest,
	ImageText,
	LinksSlices,
	NewSlice,
	TestSlice,
	TextSlice,
};

export const components = {
	content_relatsionship: ContentRelatsionship,
	image_gallery: ImageGallery,
	image_test: ImageTest,
	image_text: ImageText,
	links_slices: LinksSlices,
	new_slice: NewSlice,
	test_slice: TestSlice,
	text_slice: TextSlice,
};
